version: '3.3'

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: DwightSchrute
      POSTGRES_USER: matias
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-db:/var/lib/postgresql/data