version: '3.1'

services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: DwightSchrute
      POSTGRES_USER: matias
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-db:/var/lib/postgresql/data